[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_API_BASE_URL = "https://reflections-hcjq.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
